### ISSUE TITLE
Support for systray icons

### ISSUE THREAD

**Issue by fabolous005** [cr3eperall/dynisland#2]
Hi,

i've tested dynisland for the past few days and i really like the feels, but to effectively be able to replace my waybar i need systray icons.
Do you plan on adding support for this?
Maybe the [eww implementation](https://github.com/elkowar/eww/blob/8661abf2bf07f5a809fc995233d93810cc1ac871/crates/eww/src/widgets/systray.rs) may help...

I'm very excited to see where this project is going ;)

**Comment by cr3eperall** [comment]
I was already planning on implementing a systray module. Right now, I'm focused on refining the shared code for the modules and adding documentation, once that's done I'll probably start with this

**Comment by cr3eperall** [comment]
I've added a systray module. Let me know if you have any suggestions on how to improve it.
